# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

### OPTIONS ###
set -g mouse on
set -g base-index 1
set -g default-terminal "tmux-256color"
set -s set-clipboard on
set -s escape-time 0

### BINDING ###
bind r source-file ~/.tmux.conf
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

### STATUS LINE ###
set -g status-style bg="#2b2d31",fg="#23a559"

### VI MODE ###
bind v copy-mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
