# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#optional
set -g mouse on
set -g base-index 1
set -g default-terminal "tmux-256color"
set -s set-clipboard on

### Binding ####
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Make the status line color transparent
set -g status-style bg="#2b2d31",fg="#23a559"
